package com.example.servlets;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;  // Import WebServlet annotation
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;

@WebServlet("/CalcServlet")
public class MyServlet extends HttpServlet {
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        // Process the HTTP GET request and generate a dynamic response
        response.setContentType("text/html");
        PrintWriter out = response.getWriter();
        out.println("<html><body>");
        out.println("<h1>Hello from MyServlet!</h1>");
        out.println("<p>This is a dynamic response generated by a servlet.</p>");
        out.println("</body></html>");
    }
}
